### ISSUE TITLE
ssh connection refused after blessNewRelease

### ISSUE THREAD

**Issue by Elhebert** [nucleus-be/laravel-deploy#4]
Hi,

I have quite a strange issue with the `blessNewRelease` task. After it's finished, Envoy lost the ssh connection, and can't reconnect to it for some time, but I can still connect normally with an `ssh` command.

I tried several things like:
- commenting each line of the task to see which one was responsible, but even with only a comment, the issue occurs.
- Rename the task, didn't solve a thing.
- commenting the task for the deploy macro, and that worked.
- change the order of the tasks in the deploy macro to put `blessNewRelease` earlier in the script, and... still occurring, and strangely, it occurs after task number 10, wether it's `blessNewRelease` or not.

I haven't try to make it trigger later in the macro tho...

I don't know if it's an issue with our dev server configuration (I'm running it on a OVH vps and not on a nucleus vm) or not, but it's weird...

**Comment by mattiasgeniar** [comment]
Hi @Elhebert !

Interesting case, since it's always happening after issue 10, a couple of questions;
- any idea on timing, how long does it take before it timeouts?
- what's your ~/.ssh/config like? Does it contain a `ServerAliveInterval` config?

**Comment by Elhebert** [comment]
@mattiasgeniar I'm not sure it's a timeout issue.

It's failing to reach the server after the task. 
If I empty the tasks and leave only a comment in it, it's failing.
if don't touch the task, it'll execute everything in it, then fail to reach ssh.

Like it can't reach the remote server for the task following this one. Weird part is, I still manage to connect manually via ssh when it's telling me it's unable to connect 🤔 

And, it's not having any issue when the task is simply commented out of the macro.

I also moved the `blessNewRelease` task after the `cleanOldReleases`, and it's failing after it, so I guess it's an issue with `blessNewRelease` but I really can't figure out what...

As for my ssh config:

```
Host dev.xxx
    Hostname 1.2.3.4
    IdentityFile ~/.ssh/my-key
    Port 1234
```

I'll ask one of my co-worker to run it, to see if it's specific to my machine or not.

**Comment by Elhebert** [comment]
After sont investigation on our server, I found what caused the issue. Our firewall was limiting the rate of ssh connection.

I'm not sure on the why it was happening ONLY when the `blessNewRelease` rule was present in the macro tho. I even tried to duplicated one of the task 5 times, and it wasn't triggering the rate limit.

Maybe it was something within that particular task. But at least, now everything is running smoothly 🎉
